import SwiftUI

/// Plain-language budget insights generated by the on-device model.
struct InsightsCard: View {
    @EnvironmentObject private var store: FinanceStore

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            header
            content
        }
        .padding(16)
        .background(Theme.card, in: RoundedRectangle(cornerRadius: 14))
        .overlay(RoundedRectangle(cornerRadius: 14).strokeBorder(Theme.hairline))
    }

    private var header: some View {
        HStack(spacing: 10) {
            Image(systemName: "lightbulb.fill")
                .foregroundStyle(Theme.gold)
            Text("Insights").font(.headline)
            Spacer()
            Button {
                Task { await store.generateInsights() }
            } label: {
                if store.insights?.isGenerating == true {
                    HStack(spacing: 6) {
                        ProgressView().controlSize(.small)
                        Text("Generating")
                    }
                    .font(.caption)
                } else {
                    Label(hasText ? "Refresh" : "Generate", systemImage: "sparkles")
                        .font(.caption)
                }
            }
            .buttonStyle(.borderless)
            .disabled(store.insights?.isGenerating == true)
        }
    }

    private var hasText: Bool {
        !(store.insights?.text ?? "").isEmpty
    }

    @ViewBuilder
    private var content: some View {
        if let insights = store.insights, insights.isGenerating {
            Text("Reading this month's budget…")
                .font(.callout)
                .foregroundStyle(.secondary)
        } else if let insights = store.insights, !insights.text.isEmpty {
            VStack(alignment: .leading, spacing: 7) {
                ForEach(lines(insights.text), id: \.self) { line in
                    HStack(alignment: .top, spacing: 8) {
                        Circle()
                            .fill(Theme.gold)
                            .frame(width: 5, height: 5)
                            .padding(.top, 6)
                        Text(line)
                            .font(.callout)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
                if let when = store.insights?.generatedAt {
                    Text("Generated \(Format.relativeDate(when))")
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                        .padding(.top, 2)
                }
            }
        } else if let insights = store.insights, insights.hasError {
            Text(insights.message)
                .font(.callout)
                .foregroundStyle(Theme.red)
                .fixedSize(horizontal: false, vertical: true)
        } else {
            Text("Generate plain-language insights about how this month's spending "
                + "is tracking against your budget.")
                .font(.callout)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
    }

    private func lines(_ text: String) -> [String] {
        text
            .split(whereSeparator: \.isNewline)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
    }
}
